name: Hotel News
favicon: null
layout_spectrum: 0.5559490306768566
typography_spectrum: 0.6624196688644588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48729667835868895
  lightness: 0.01064511970616877
  saturation: 0.8898983739782125
  rhythmicContrast: 0.7661065002903342
purpose: []
