name: Hotel News
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28503
title: 'Hotel & Travel Industry News'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76826127-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48729667835868895
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
